// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    setUp: function(callback) {
      this.Encrypt = require('./encrypt');
      return callback();
    },
    tearDown: function(callback) {
      return callback();
    },
    testEncrypt: function(test) {
      var actual, expected, src;
      src = 'Hello,CryptWorld';
      actual = 'rh7ro9NH1XZeLX95paLETDgYxRbnDoOIrxarO0Sy73s=';
      expected = this.Encrypt.encrypt(src);
      test.equals(actual, expected);
      return test.done();
    },
    testDescrypt: function(test) {
      var actual, expected, src;
      src = 'rh7ro9NH1XZeLX95paLETDgYxRbnDoOIrxarO0Sy73s=';
      actual = 'Hello,CryptWorld';
      expected = this.Encrypt.decrypt(src);
      test.equals(actual, expected);
      return test.done();
    }
  };

}).call(this);
